# Generated by Django 3.0.5 on 2020-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dwelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=4000)),
                ('category_id', models.IntegerField(default=0)),
                ('property_id', models.IntegerField(default=0)),
                ('city_id', models.IntegerField()),
                ('address', models.TextField(max_length=4000)),
                ('rating', models.IntegerField(default=0)),
                ('person_capacity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
