# Generated by Django 3.0.5 on 2020-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='bed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dwelling',
            name='bedroom_count',
            field=models.IntegerField(default=0),
        ),
    ]
