# Generated by Django 3.0.5 on 2020-04-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0004_categories_cities_dwellingimages_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
        migrations.RemoveField(
            model_name='dwellingimages',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='property_id',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='DwellingImages',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
