# Generated by Django 3.0.5 on 2020-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0006_categories_cities_dwellingimages_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwelling',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
