# Generated by Django 3.0.5 on 2020-04-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0007_auto_20200410_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='bath_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='categories',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cities',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dwellingimages',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
