# Generated by Django 3.0.5 on 2020-04-11 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0009_auto_20200411_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dwelling',
            old_name='publis',
            new_name='publish',
        ),
    ]
