# Generated by Django 3.0.5 on 2020-04-12 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0010_auto_20200411_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwellingimages',
            name='property_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_images', to='container.Dwelling'),
        ),
    ]
