# Generated by Django 3.0.5 on 2020-04-12 02:27

import container.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0011_auto_20200412_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwellingimages',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 12, 2, 27, 15, 952373, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dwellingimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=container.models.upload_location),
        ),
    ]
