# Generated by Django 3.0.5 on 2020-04-12 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0012_auto_20200412_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='categories',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 4, 12, 2, 29, 11, 141075, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
