# Generated by Django 3.0.5 on 2020-04-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0013_auto_20200412_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='city_id',
        ),
    ]
