# Generated by Django 3.0.5 on 2020-04-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0015_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
