# Generated by Django 3.0.5 on 2020-04-12 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0016_amenities_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='description',
        ),
    ]
