# Generated by Django 3.0.5 on 2020-04-12 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0018_propertytypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dwell_reviews', to='container.Dwelling'),
        ),
    ]
