# Generated by Django 3.0.5 on 2020-04-12 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0020_amenities_property_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenities',
            name='property_id',
        ),
    ]
