# Generated by Django 3.0.5 on 2020-04-12 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0022_auto_20200412_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='property_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_amenities', to='container.Dwelling'),
        ),
    ]
