# Generated by Django 3.0.5 on 2020-04-12 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0023_amenities_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dwelling',
            name='property_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='property_type', to='container.PropertyTypes'),
        ),
    ]
