# Generated by Django 3.0.5 on 2020-04-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0024_dwelling_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dwelling',
            name='bath_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='bed_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='bedroom_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='person_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='dwelling',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
